"""Check lessons/glossary.js against the lessons and rebuild GLOSSARY.md.

Plain Python 3, no installs:  python3 tools/glossary.py
  * lists words used in lessons that have no glossary entry (add them!)
  * lists glossary words no lesson uses any more
  * writes GLOSSARY.md: words grouped by the lesson that introduced them,
    with meanings and the other lessons that reuse them
"""
import json
import re
import sys
import unicodedata
from pathlib import Path

VN = Path(__file__).resolve().parent.parent


def nfc(s):
    return unicodedata.normalize("NFC", s)


def load_js(path, start_char):
    text = path.read_text(encoding="utf-8")
    text = "\n".join(l for l in text.splitlines() if not l.strip().startswith("//"))
    body = text[text.index(start_char): text.rindex("]" if start_char == "[" else "}") + 1]
    body = re.sub(r'([{,]\s*)([A-Za-z_]\w*)\s*:', r'\1"\2":', body)  # quote bare keys after { or ,
    body = re.sub(r",\s*([\]}])", r"\1", body)                          # trailing commas
    return json.loads(body)


def words_of(sentence):
    return [nfc(w.lower()) for w in (re.sub(r"[^\w]", "", t) for t in sentence.split()) if w]


def main():
    lessons = load_js(VN / "lessons" / "lessons.js", "[")
    # Workbook pages (Chọn Từ game) add their filled-in sentences too.
    sys.path.insert(0, str(VN / "tools"))
    sys.dont_write_bytecode = True
    from make_voices import workbook_as_lessons, poems_as_lessons
    lessons += workbook_as_lessons() + poems_as_lessons()
    gloss = load_js(VN / "lessons" / "glossary.js", "{")
    words = {nfc(k): v for k, v in gloss.get("words", {}).items()}
    phrases = {nfc(k): v for k, v in gloss.get("phrases", {}).items()}

    first, uses, order = {}, {}, []
    for lesson in lessons:
        for sent in lesson["sentences"]:
            for w in words_of(sent[0]):
                if w not in first:
                    first[w] = lesson["id"]
                    order.append(w)
                uses.setdefault(w, [])
                if lesson["id"] not in uses[w]:
                    uses[w].append(lesson["id"])

    missing = [w for w in order if w not in words]

    # align: every Vietnamese word should point at English text that really exists
    align_problems = []
    for lesson in lessons:
        if "align" not in lesson:
            continue  # workbook pages: no per-word English alignment
        align = lesson.get("align") or []
        for i, sent in enumerate(lesson["sentences"]):
            a = align[i] if i < len(align) else {}
            vi_words = words_of(sent[0])
            for key, val in a.items():
                for t in (val if isinstance(val, list) else [val]):
                    if not re.search(r"(?<!\w)" + re.escape(t) + r"(?!\w)", sent[1]):
                        align_problems.append(f"{lesson['id']}:{i + 1} '{key}' -> '{t}' not found in English")
                if nfc(key) not in vi_words:
                    align_problems.append(f"{lesson['id']}:{i + 1} '{key}' is not a word in the sentence")
            unmatched = [w for w in vi_words if w not in {nfc(k) for k in a}]
            if unmatched:
                align_problems.append(f"{lesson['id']}:{i + 1} no English match for: {', '.join(unmatched)} (ok if none exists)")
    unused = [w for w in words if w not in first]

    titles = {l["id"]: l["title"] + (f" · {l['focus']}" if l.get("focus") else "") for l in lessons}
    out = ["# Vietnamese glossary", "",
           "Generated by `tools/glossary.py` from `lessons/lessons.js` and `lessons/glossary.js`. "
           "Edit those files, not this one.", "",
           f"{len(first)} words across {len(lessons)} lesson(s).", ""]
    for lesson in lessons:
        new = [w for w in order if first[w] == lesson["id"]]
        if not new:
            continue
        out += [f"## {titles[lesson['id']]} — {len(new)} new", "",
                "| Word | Meaning | Note | Also in |", "| --- | --- | --- | --- |"]
        for w in new:
            e = words.get(w, {})
            also = ", ".join(titles[x] for x in uses[w] if x != lesson["id"])
            out.append(f"| **{w}** | {e.get('en', '❓ missing')} | {e.get('note', '')} | {also} |")
        out.append("")
    if phrases:
        out += ["## Phrases", "", "| Phrase | Meaning |", "| --- | --- |"]
        out += [f"| **{p}** | {e.get('en', '')} |" for p, e in phrases.items()]
        out.append("")
    (VN / "GLOSSARY.md").write_text("\n".join(out), encoding="utf-8")

    print(f"{len(first)} words in lessons, {len(words)} in glossary. Wrote GLOSSARY.md")
    if missing:
        print("Missing from glossary:", ", ".join(missing))
    for p in align_problems:
        print("Align:", p)
    if unused:
        print("In glossary but not in any lesson:", ", ".join(unused))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
