// Generated by tools/make_voices.py. Paths are relative to VN/audio/.
window.VN_AUDIO = {
  "voices": [
    {
      "id": "sample3",
      "label": "Sample3",
      "lessons": {
        "bai-1": {
          "sentences": [
            "sample3/bai-1/s01.m4a",
            "sample3/bai-1/s02.m4a",
            "sample3/bai-1/s03.m4a",
            "sample3/bai-1/s04.m4a",
            "sample3/bai-1/s05.m4a",
            "sample3/bai-1/s06.m4a",
            "sample3/bai-1/s07.m4a",
            "sample3/bai-1/s08.m4a",
            "sample3/bai-1/s09.m4a"
          ],
          "words": {
            "ba": "sample3/bai-1/words/ba.m4a",
            "bé": "sample3/bai-1/words/bé.m4a",
            "bò": "sample3/bai-1/words/bò.m4a",
            "bờ": "sample3/bai-1/words/bờ.m4a",
            "cha": "sample3/bai-1/words/cha.m4a",
            "cát": "sample3/bai-1/words/cát.m4a",
            "dữ": "sample3/bai-1/words/dữ.m4a",
            "em": "sample3/bai-1/words/em.m4a",
            "ghe": "sample3/bai-1/words/ghe.m4a",
            "ghi": "sample3/bai-1/words/ghi.m4a",
            "ghé": "sample3/bai-1/words/ghé.m4a",
            "ghê": "sample3/bai-1/words/ghê.m4a",
            "ghì": "sample3/bai-1/words/ghì.m4a",
            "ghẹ": "sample3/bai-1/words/ghẹ.m4a",
            "ghẻ": "sample3/bai-1/words/ghẻ.m4a",
            "ghế": "sample3/bai-1/words/ghế.m4a",
            "hổ": "sample3/bai-1/words/hổ.m4a",
            "lở": "sample3/bai-1/words/lở.m4a",
            "má": "sample3/bai-1/words/má.m4a",
            "mẹ": "sample3/bai-1/words/mẹ.m4a",
            "ngồi": "sample3/bai-1/words/ngồi.m4a",
            "sổ": "sample3/bai-1/words/sổ.m4a",
            "sợ": "sample3/bai-1/words/sợ.m4a",
            "trên": "sample3/bai-1/words/trên.m4a",
            "vô": "sample3/bai-1/words/vô.m4a",
            "đi": "sample3/bai-1/words/đi.m4a",
            "ơn": "sample3/bai-1/words/ơn.m4a"
          }
        }
      }
    }
  ]
};
